// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.mod;

public enum Platform {

	UNKNOW(0),
	Ios(1),
	Android(2),
	PC(3),
	H5(4),
	TV(5),
	IosPad(6),
	AndroidPad(7);

	private final int value;

	private Platform(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static Platform convert(int value) {
		for(Platform v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
