// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AliPayInfo {

	@TarsStructProperty(order = 0, isRequire = true)
	public String payInfo = "";

	public String getPayInfo() {
		return payInfo;
	}

	public void setPayInfo(String payInfo) {
		this.payInfo = payInfo;
	}

	public AliPayInfo() {
	}

	public AliPayInfo(String payInfo) {
		this.payInfo = payInfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(payInfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AliPayInfo)) {
			return false;
		}
		AliPayInfo other = (AliPayInfo) obj;
		return (
			TarsUtil.equals(payInfo, other.payInfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(payInfo, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.payInfo = _is.readString(0, true);
	}

}
