// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class ChangePasswordRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String oldPassword = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String newPassword = "";

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	public ChangePasswordRequest() {
	}

	public ChangePasswordRequest(String oldPassword, String newPassword) {
		this.oldPassword = oldPassword;
		this.newPassword = newPassword;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(oldPassword);
		result = prime * result + TarsUtil.hashCode(newPassword);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ChangePasswordRequest)) {
			return false;
		}
		ChangePasswordRequest other = (ChangePasswordRequest) obj;
		return (
			TarsUtil.equals(oldPassword, other.oldPassword) &&
			TarsUtil.equals(newPassword, other.newPassword) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(oldPassword, 0);
		_os.write(newPassword, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.oldPassword = _is.readString(0, true);
		this.newPassword = _is.readString(1, true);
	}

}
