// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetProductResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<Product> products = null;

	public java.util.List<Product> getProducts() {
		return products;
	}

	public void setProducts(java.util.List<Product> products) {
		this.products = products;
	}

	public GetProductResponse() {
	}

	public GetProductResponse(java.util.List<Product> products) {
		this.products = products;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(products);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetProductResponse)) {
			return false;
		}
		GetProductResponse other = (GetProductResponse) obj;
		return (
			TarsUtil.equals(products, other.products) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(products, 0);
	}

	static java.util.List<Product> cache_products;
	static { 
		cache_products = new java.util.ArrayList<Product>();
		Product var_5 = new Product();
		cache_products.add(var_5);
	}

	public void readFrom(TarsInputStream _is) {
		this.products = (java.util.List<Product>) _is.read(cache_products, 0, true);
	}

}
