// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class GetVerifyCodeRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String mobilePhone = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int type = 0;

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public GetVerifyCodeRequest() {
	}

	public GetVerifyCodeRequest(String mobilePhone, int type) {
		this.mobilePhone = mobilePhone;
		this.type = type;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(mobilePhone);
		result = prime * result + TarsUtil.hashCode(type);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof GetVerifyCodeRequest)) {
			return false;
		}
		GetVerifyCodeRequest other = (GetVerifyCodeRequest) obj;
		return (
			TarsUtil.equals(mobilePhone, other.mobilePhone) &&
			TarsUtil.equals(type, other.type) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(mobilePhone, 0);
		_os.write(type, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.mobilePhone = _is.readString(0, true);
		this.type = _is.read(type, 1, false);
	}

}
