// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class LoginWechatRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String wxLoginCode = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String wxEncryptData = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String wxIV = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public boolean noCreate = false;

	public String getWxLoginCode() {
		return wxLoginCode;
	}

	public void setWxLoginCode(String wxLoginCode) {
		this.wxLoginCode = wxLoginCode;
	}

	public String getWxEncryptData() {
		return wxEncryptData;
	}

	public void setWxEncryptData(String wxEncryptData) {
		this.wxEncryptData = wxEncryptData;
	}

	public String getWxIV() {
		return wxIV;
	}

	public void setWxIV(String wxIV) {
		this.wxIV = wxIV;
	}

	public boolean getNoCreate() {
		return noCreate;
	}

	public void setNoCreate(boolean noCreate) {
		this.noCreate = noCreate;
	}

	public LoginWechatRequest() {
	}

	public LoginWechatRequest(String wxLoginCode, String wxEncryptData, String wxIV, boolean noCreate) {
		this.wxLoginCode = wxLoginCode;
		this.wxEncryptData = wxEncryptData;
		this.wxIV = wxIV;
		this.noCreate = noCreate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(wxLoginCode);
		result = prime * result + TarsUtil.hashCode(wxEncryptData);
		result = prime * result + TarsUtil.hashCode(wxIV);
		result = prime * result + TarsUtil.hashCode(noCreate);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof LoginWechatRequest)) {
			return false;
		}
		LoginWechatRequest other = (LoginWechatRequest) obj;
		return (
			TarsUtil.equals(wxLoginCode, other.wxLoginCode) &&
			TarsUtil.equals(wxEncryptData, other.wxEncryptData) &&
			TarsUtil.equals(wxIV, other.wxIV) &&
			TarsUtil.equals(noCreate, other.noCreate) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(wxLoginCode, 0);
		if (null != wxEncryptData) {
			_os.write(wxEncryptData, 1);
		}
		if (null != wxIV) {
			_os.write(wxIV, 2);
		}
		_os.write(noCreate, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.wxLoginCode = _is.readString(0, true);
		this.wxEncryptData = _is.readString(1, false);
		this.wxIV = _is.readString(2, false);
		this.noCreate = _is.read(noCreate, 3, false);
	}

}
