// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class LoginRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public String username = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String password = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String wxLoginCode = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String wxEncryptData = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String wxIV = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String verifyCode = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public String wxAppId = "";

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getWxLoginCode() {
		return wxLoginCode;
	}

	public void setWxLoginCode(String wxLoginCode) {
		this.wxLoginCode = wxLoginCode;
	}

	public String getWxEncryptData() {
		return wxEncryptData;
	}

	public void setWxEncryptData(String wxEncryptData) {
		this.wxEncryptData = wxEncryptData;
	}

	public String getWxIV() {
		return wxIV;
	}

	public void setWxIV(String wxIV) {
		this.wxIV = wxIV;
	}

	public String getVerifyCode() {
		return verifyCode;
	}

	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}

	public String getWxAppId() {
		return wxAppId;
	}

	public void setWxAppId(String wxAppId) {
		this.wxAppId = wxAppId;
	}

	public LoginRequest() {
	}

	public LoginRequest(String username, String password, String wxLoginCode, String wxEncryptData, String wxIV, String verifyCode, String wxAppId) {
		this.username = username;
		this.password = password;
		this.wxLoginCode = wxLoginCode;
		this.wxEncryptData = wxEncryptData;
		this.wxIV = wxIV;
		this.verifyCode = verifyCode;
		this.wxAppId = wxAppId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(username);
		result = prime * result + TarsUtil.hashCode(password);
		result = prime * result + TarsUtil.hashCode(wxLoginCode);
		result = prime * result + TarsUtil.hashCode(wxEncryptData);
		result = prime * result + TarsUtil.hashCode(wxIV);
		result = prime * result + TarsUtil.hashCode(verifyCode);
		result = prime * result + TarsUtil.hashCode(wxAppId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof LoginRequest)) {
			return false;
		}
		LoginRequest other = (LoginRequest) obj;
		return (
			TarsUtil.equals(username, other.username) &&
			TarsUtil.equals(password, other.password) &&
			TarsUtil.equals(wxLoginCode, other.wxLoginCode) &&
			TarsUtil.equals(wxEncryptData, other.wxEncryptData) &&
			TarsUtil.equals(wxIV, other.wxIV) &&
			TarsUtil.equals(verifyCode, other.verifyCode) &&
			TarsUtil.equals(wxAppId, other.wxAppId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(username, 0);
		_os.write(password, 1);
		if (null != wxLoginCode) {
			_os.write(wxLoginCode, 2);
		}
		if (null != wxEncryptData) {
			_os.write(wxEncryptData, 3);
		}
		if (null != wxIV) {
			_os.write(wxIV, 4);
		}
		if (null != verifyCode) {
			_os.write(verifyCode, 5);
		}
		if (null != wxAppId) {
			_os.write(wxAppId, 6);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.username = _is.readString(0, true);
		this.password = _is.readString(1, true);
		this.wxLoginCode = _is.readString(2, false);
		this.wxEncryptData = _is.readString(3, false);
		this.wxIV = _is.readString(4, false);
		this.verifyCode = _is.readString(5, false);
		this.wxAppId = _is.readString(6, false);
	}

}
