// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PlaceOrderRequest {

	@TarsStructProperty(order = 0, isRequire = true)
	public int productId = 0;
	@TarsStructProperty(order = 1, isRequire = true)
	public int payType = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public String ext = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String iapReceipt = "";

	public int getProductId() {
		return productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getPayType() {
		return payType;
	}

	public void setPayType(int payType) {
		this.payType = payType;
	}

	public String getExt() {
		return ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public String getIapReceipt() {
		return iapReceipt;
	}

	public void setIapReceipt(String iapReceipt) {
		this.iapReceipt = iapReceipt;
	}

	public PlaceOrderRequest() {
	}

	public PlaceOrderRequest(int productId, int payType, String ext, String iapReceipt) {
		this.productId = productId;
		this.payType = payType;
		this.ext = ext;
		this.iapReceipt = iapReceipt;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(productId);
		result = prime * result + TarsUtil.hashCode(payType);
		result = prime * result + TarsUtil.hashCode(ext);
		result = prime * result + TarsUtil.hashCode(iapReceipt);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PlaceOrderRequest)) {
			return false;
		}
		PlaceOrderRequest other = (PlaceOrderRequest) obj;
		return (
			TarsUtil.equals(productId, other.productId) &&
			TarsUtil.equals(payType, other.payType) &&
			TarsUtil.equals(ext, other.ext) &&
			TarsUtil.equals(iapReceipt, other.iapReceipt) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(productId, 0);
		_os.write(payType, 1);
		if (null != ext) {
			_os.write(ext, 2);
		}
		if (null != iapReceipt) {
			_os.write(iapReceipt, 3);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.productId = _is.read(productId, 0, true);
		this.payType = _is.read(payType, 1, true);
		this.ext = _is.readString(2, false);
		this.iapReceipt = _is.readString(3, false);
	}

}
