// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class RegisterWechatResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public User userInfo = null;
	@TarsStructProperty(order = 1, isRequire = true)
	public boolean isCreated = false;

	public User getUserInfo() {
		return userInfo;
	}

	public void setUserInfo(User userInfo) {
		this.userInfo = userInfo;
	}

	public boolean isCreated() {
		return isCreated;
	}

	public void setCreated(boolean isCreated) {
		this.isCreated = isCreated;
	}

	public RegisterWechatResponse() {
	}

	public RegisterWechatResponse(User userInfo, boolean isCreated) {
		this.userInfo = userInfo;
		this.isCreated = isCreated;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userInfo);
		result = prime * result + TarsUtil.hashCode(isCreated);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RegisterWechatResponse)) {
			return false;
		}
		RegisterWechatResponse other = (RegisterWechatResponse) obj;
		return (
			TarsUtil.equals(userInfo, other.userInfo) &&
			TarsUtil.equals(isCreated, other.isCreated) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(userInfo, 0);
		_os.write(isCreated, 1);
	}

	static User cache_userInfo;
	static { 
		cache_userInfo = new User();
	}

	public void readFrom(TarsInputStream _is) {
		this.userInfo = (User) _is.read(cache_userInfo, 0, true);
		this.isCreated = _is.read(isCreated, 1, true);
	}

}
