// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class RegisterResponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public User userInfo = null;

	public User getUserInfo() {
		return userInfo;
	}

	public void setUserInfo(User userInfo) {
		this.userInfo = userInfo;
	}

	public RegisterResponse() {
	}

	public RegisterResponse(User userInfo) {
		this.userInfo = userInfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userInfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RegisterResponse)) {
			return false;
		}
		RegisterResponse other = (RegisterResponse) obj;
		return (
			TarsUtil.equals(userInfo, other.userInfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(userInfo, 0);
	}

	static User cache_userInfo;
	static { 
		cache_userInfo = new User();
	}

	public void readFrom(TarsInputStream _is) {
		this.userInfo = (User) _is.read(cache_userInfo, 0, true);
	}

}
