// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class UpdateUserInfoResponse {

	@TarsStructProperty(order = 0, isRequire = false)
	public User user = null;

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public UpdateUserInfoResponse() {
	}

	public UpdateUserInfoResponse(User user) {
		this.user = user;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(user);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof UpdateUserInfoResponse)) {
			return false;
		}
		UpdateUserInfoResponse other = (UpdateUserInfoResponse) obj;
		return (
			TarsUtil.equals(user, other.user) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != user) {
			_os.write(user, 0);
		}
	}

	static User cache_user;
	static { 
		cache_user = new User();
	}

	public void readFrom(TarsInputStream _is) {
		this.user = (User) _is.read(cache_user, 0, false);
	}

}
