// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.kingsunsoft.sdk.modsdk;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class UpdateUserInfoRequest {

	@TarsStructProperty(order = 0, isRequire = false)
	public String name = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String avatar = "";

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public UpdateUserInfoRequest() {
	}

	public UpdateUserInfoRequest(String name, String avatar) {
		this.name = name;
		this.avatar = avatar;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(avatar);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof UpdateUserInfoRequest)) {
			return false;
		}
		UpdateUserInfoRequest other = (UpdateUserInfoRequest) obj;
		return (
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(avatar, other.avatar) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != name) {
			_os.write(name, 0);
		}
		if (null != avatar) {
			_os.write(avatar, 1);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.name = _is.readString(0, false);
		this.avatar = _is.readString(1, false);
	}

}
